/* Generated By:JavaCC: Do not edit this line. GraphReaderTLPParserConstants.java */
package org.graphstream.io.tlp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GraphReaderTLPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int TLP = 9;
  /** RegularExpression Id. */
  int DATE = 10;
  /** RegularExpression Id. */
  int AUTHOR = 11;
  /** RegularExpression Id. */
  int COMMENTS = 12;
  /** RegularExpression Id. */
  int NODES = 13;
  /** RegularExpression Id. */
  int NODE = 14;
  /** RegularExpression Id. */
  int EDGES = 15;
  /** RegularExpression Id. */
  int EDGE = 16;
  /** RegularExpression Id. */
  int CLUSTER = 17;
  /** RegularExpression Id. */
  int PROPERTY = 18;
  /** RegularExpression Id. */
  int DEF = 19;
  /** RegularExpression Id. */
  int PTYPES = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int STRING = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<EOL>",
    "<COMMENT>",
    "\"(\"",
    "\")\"",
    "\"tlp\"",
    "\"date\"",
    "\"author\"",
    "\"comments\"",
    "\"nodes\"",
    "\"node\"",
    "\"edges\"",
    "\"edge\"",
    "\"cluster\"",
    "\"property\"",
    "\"default\"",
    "<PTYPES>",
    "<ID>",
    "<STRING>",
  };

}
