/* Generated By:JavaCC: Do not edit this line. GMLParserConstants.java */
package org.graphstream.stream.file.gml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int HEXDIGIT = 7;
  /** RegularExpression Id. */
  int LSQBR = 8;
  /** RegularExpression Id. */
  int RSQBR = 9;
  /** RegularExpression Id. */
  int REAL = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int GRAPH = 12;
  /** RegularExpression Id. */
  int DIGRAPH = 13;
  /** RegularExpression Id. */
  int KEY = 14;
  /** RegularExpression Id. */
  int COMMENT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<EOL>",
    "<DIGIT>",
    "<HEXDIGIT>",
    "\"[\"",
    "\"]\"",
    "<REAL>",
    "<STRING>",
    "\"graph\"",
    "\"digraph\"",
    "<KEY>",
    "<COMMENT>",
  };

}
