/* Generated By:JavaCC: Do not edit this line. DOTParserConstants.java */
package org.graphstream.stream.file.dot;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DOTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int HEXDIGIT = 9;
  /** RegularExpression Id. */
  int LSQBR = 10;
  /** RegularExpression Id. */
  int RSQBR = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int GRAPH = 17;
  /** RegularExpression Id. */
  int DIGRAPH = 18;
  /** RegularExpression Id. */
  int SUBGRAPH = 19;
  /** RegularExpression Id. */
  int NODE = 20;
  /** RegularExpression Id. */
  int EDGE = 21;
  /** RegularExpression Id. */
  int STRICT = 22;
  /** RegularExpression Id. */
  int EDGE_OP = 23;
  /** RegularExpression Id. */
  int REAL = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int WORD = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<EOL>",
    "<DIGIT>",
    "<HEXDIGIT>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\"graph\"",
    "\"digraph\"",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "\"strict\"",
    "<EDGE_OP>",
    "<REAL>",
    "<STRING>",
    "<WORD>",
    "\";\"",
    "\"n\"",
    "\"ne\"",
    "\"e\"",
    "\"se\"",
    "\"s\"",
    "\"sw\"",
    "\"w\"",
    "\"nw\"",
    "\"c\"",
    "\"_\"",
  };

}
