/* Generated By:JavaCC: Do not edit this line. StyleSheetParserConstants.java */
package org.graphstream.ui.graphicGraph.stylesheet.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface StyleSheetParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int EOL = 5;
	/** RegularExpression Id. */
	int DIGIT = 6;
	/** RegularExpression Id. */
	int HEXDIGIT = 7;
	/** RegularExpression Id. */
	int UNITS = 8;
	/** RegularExpression Id. */
	int DOT = 9;
	/** RegularExpression Id. */
	int LBRACE = 10;
	/** RegularExpression Id. */
	int RBRACE = 11;
	/** RegularExpression Id. */
	int LPAREN = 12;
	/** RegularExpression Id. */
	int RPAREN = 13;
	/** RegularExpression Id. */
	int SHARP = 14;
	/** RegularExpression Id. */
	int COLON = 15;
	/** RegularExpression Id. */
	int SEMICOLON = 16;
	/** RegularExpression Id. */
	int COMA = 17;
	/** RegularExpression Id. */
	int RGBA = 18;
	/** RegularExpression Id. */
	int RGB = 19;
	/** RegularExpression Id. */
	int HTMLCOLOR = 20;
	/** RegularExpression Id. */
	int REAL = 21;
	/** RegularExpression Id. */
	int STRING = 22;
	/** RegularExpression Id. */
	int URL = 23;
	/** RegularExpression Id. */
	int GRAPH = 24;
	/** RegularExpression Id. */
	int EDGE = 25;
	/** RegularExpression Id. */
	int NODE = 26;
	/** RegularExpression Id. */
	int SPRITE = 27;
	/** RegularExpression Id. */
	int FILLMODE = 28;
	/** RegularExpression Id. */
	int FILLCOLOR = 29;
	/** RegularExpression Id. */
	int FILLIMAGE = 30;
	/** RegularExpression Id. */
	int STROKEMODE = 31;
	/** RegularExpression Id. */
	int STROKECOLOR = 32;
	/** RegularExpression Id. */
	int STROKEWIDTH = 33;
	/** RegularExpression Id. */
	int SHADOWMODE = 34;
	/** RegularExpression Id. */
	int SHADOWCOLOR = 35;
	/** RegularExpression Id. */
	int SHADOWWIDTH = 36;
	/** RegularExpression Id. */
	int SHADOWOFFSET = 37;
	/** RegularExpression Id. */
	int TEXTMODE = 38;
	/** RegularExpression Id. */
	int TEXTCOLOR = 39;
	/** RegularExpression Id. */
	int TEXTSTYLE = 40;
	/** RegularExpression Id. */
	int TEXTFONT = 41;
	/** RegularExpression Id. */
	int TEXTSIZE = 42;
	/** RegularExpression Id. */
	int TEXTVISIBILITYMODE = 43;
	/** RegularExpression Id. */
	int TEXTVISIBILITY = 44;
	/** RegularExpression Id. */
	int TEXTBACKGROUNDMODE = 45;
	/** RegularExpression Id. */
	int TEXTBACKGROUNDCOLOR = 46;
	/** RegularExpression Id. */
	int ICONMODE = 47;
	/** RegularExpression Id. */
	int ICON = 48;
	/** RegularExpression Id. */
	int PADDING = 49;
	/** RegularExpression Id. */
	int ZINDEX = 50;
	/** RegularExpression Id. */
	int VISIBILITYMODE = 51;
	/** RegularExpression Id. */
	int VISIBILITY = 52;
	/** RegularExpression Id. */
	int SHAPE = 53;
	/** RegularExpression Id. */
	int SIZE = 54;
	/** RegularExpression Id. */
	int SIZEMODE = 55;
	/** RegularExpression Id. */
	int SHAPEPOINTS = 56;
	/** RegularExpression Id. */
	int TEXTALIGNMENT = 57;
	/** RegularExpression Id. */
	int JCOMPONENT = 58;
	/** RegularExpression Id. */
	int ARROWIMGURL = 59;
	/** RegularExpression Id. */
	int ARROWSIZE = 60;
	/** RegularExpression Id. */
	int ARROWSHAPE = 61;
	/** RegularExpression Id. */
	int SPRITEORIENT = 62;
	/** RegularExpression Id. */
	int CANVASCOLOR = 63;
	/** RegularExpression Id. */
	int PLAIN = 64;
	/** RegularExpression Id. */
	int DYNPLAIN = 65;
	/** RegularExpression Id. */
	int DYNSIZE = 66;
	/** RegularExpression Id. */
	int DYNICON = 67;
	/** RegularExpression Id. */
	int DASHES = 68;
	/** RegularExpression Id. */
	int DOTS = 69;
	/** RegularExpression Id. */
	int GRADIENTDIAGONAL1 = 70;
	/** RegularExpression Id. */
	int GRADIENTDIAGONAL2 = 71;
	/** RegularExpression Id. */
	int GRADIENTHORIZONTAL = 72;
	/** RegularExpression Id. */
	int GRADIENTRADIAL = 73;
	/** RegularExpression Id. */
	int GRADIENTVERTICAL = 74;
	/** RegularExpression Id. */
	int HIDDEN = 75;
	/** RegularExpression Id. */
	int IMAGETILED = 76;
	/** RegularExpression Id. */
	int IMAGESCALED = 77;
	/** RegularExpression Id. */
	int IMAGESCALEDRATIOMAX = 78;
	/** RegularExpression Id. */
	int IMAGESCALEDRATIOMIN = 79;
	/** RegularExpression Id. */
	int NONE = 80;
	/** RegularExpression Id. */
	int NORMAL = 81;
	/** RegularExpression Id. */
	int TRUNCATED = 82;
	/** RegularExpression Id. */
	int ZOOMRANGE = 83;
	/** RegularExpression Id. */
	int ATZOOM = 84;
	/** RegularExpression Id. */
	int UNDERZOOM = 85;
	/** RegularExpression Id. */
	int OVERZOOM = 86;
	/** RegularExpression Id. */
	int ZOOMS = 87;
	/** RegularExpression Id. */
	int FIT = 88;
	/** RegularExpression Id. */
	int BOLD = 89;
	/** RegularExpression Id. */
	int BOLD_ITALIC = 90;
	/** RegularExpression Id. */
	int ITALIC = 91;
	/** RegularExpression Id. */
	int ALONG = 92;
	/** RegularExpression Id. */
	int ATLEFT = 93;
	/** RegularExpression Id. */
	int ATRIGHT = 94;
	/** RegularExpression Id. */
	int CENTER = 95;
	/** RegularExpression Id. */
	int LEFT = 96;
	/** RegularExpression Id. */
	int RIGHT = 97;
	/** RegularExpression Id. */
	int UNDER = 98;
	/** RegularExpression Id. */
	int ABOVE = 99;
	/** RegularExpression Id. */
	int JUSTIFY = 100;
	/** RegularExpression Id. */
	int CIRCLE = 101;
	/** RegularExpression Id. */
	int TRIANGLE = 102;
	/** RegularExpression Id. */
	int FREEPLANE = 103;
	/** RegularExpression Id. */
	int TEXTBOX = 104;
	/** RegularExpression Id. */
	int TEXTROUNDEDBOX = 105;
	/** RegularExpression Id. */
	int TEXTCIRCLE = 106;
	/** RegularExpression Id. */
	int TEXTDIAMOND = 107;
	/** RegularExpression Id. */
	int TEXTPARAGRAPH = 108;
	/** RegularExpression Id. */
	int BOX = 109;
	/** RegularExpression Id. */
	int ROUNDEDBOX = 110;
	/** RegularExpression Id. */
	int CROSS = 111;
	/** RegularExpression Id. */
	int DIAMOND = 112;
	/** RegularExpression Id. */
	int POLYGON = 113;
	/** RegularExpression Id. */
	int BUTTON = 114;
	/** RegularExpression Id. */
	int TEXTFIELD = 115;
	/** RegularExpression Id. */
	int PANEL = 116;
	/** RegularExpression Id. */
	int LINE = 117;
	/** RegularExpression Id. */
	int POLYLINE = 118;
	/** RegularExpression Id. */
	int ANGLE = 119;
	/** RegularExpression Id. */
	int CUBICCURVE = 120;
	/** RegularExpression Id. */
	int BLOB = 121;
	/** RegularExpression Id. */
	int ARROW = 122;
	/** RegularExpression Id. */
	int FLOW = 123;
	/** RegularExpression Id. */
	int PIECHART = 124;
	/** RegularExpression Id. */
	int IMAGE = 125;
	/** RegularExpression Id. */
	int IMAGES = 126;
	/** RegularExpression Id. */
	int FROM = 127;
	/** RegularExpression Id. */
	int NODE0 = 128;
	/** RegularExpression Id. */
	int TO = 129;
	/** RegularExpression Id. */
	int NODE1 = 130;
	/** RegularExpression Id. */
	int PROJECTION = 131;
	/** RegularExpression Id. */
	int CLICKED = 132;
	/** RegularExpression Id. */
	int SELECTED = 133;
	/** RegularExpression Id. */
	int IDENTIFIER = 134;
	/** RegularExpression Id. */
	int COMMENT = 135;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"",
			"<EOL>", "<DIGIT>", "<HEXDIGIT>", "<UNITS>", "\".\"", "\"{\"",
			"\"}\"", "\"(\"", "\")\"", "\"#\"", "\":\"", "\";\"", "\",\"",
			"<RGBA>", "<RGB>", "<HTMLCOLOR>", "<REAL>", "<STRING>", "\"url\"",
			"\"graph\"", "\"edge\"", "\"node\"", "\"sprite\"", "\"fill-mode\"",
			"\"fill-color\"", "\"fill-image\"", "\"stroke-mode\"",
			"\"stroke-color\"", "\"stroke-width\"", "\"shadow-mode\"",
			"\"shadow-color\"", "\"shadow-width\"", "\"shadow-offset\"",
			"\"text-mode\"", "\"text-color\"", "\"text-style\"",
			"\"text-font\"", "\"text-size\"", "\"text-visibility-mode\"",
			"\"text-visibility\"", "\"text-background-mode\"",
			"\"text-background-color\"", "\"icon-mode\"", "\"icon\"",
			"\"padding\"", "\"z-index\"", "\"visibility-mode\"",
			"\"visibility\"", "\"shape\"", "\"size\"", "\"size-mode\"",
			"\"shape-points\"", "\"text-alignment\"", "\"jcomponent\"",
			"\"arrow-image\"", "\"arrow-size\"", "\"arrow-shape\"",
			"\"sprite-orientation\"", "\"canvas-color\"", "\"plain\"",
			"\"dyn-plain\"", "\"dyn-size\"", "\"dyn-icon\"", "\"dashes\"",
			"\"dots\"", "\"gradient-diagonal1\"", "\"gradient-diagonal2\"",
			"\"gradient-horizontal\"", "\"gradient-radial\"",
			"\"gradient-vertical\"", "\"hidden\"", "\"image-tiled\"",
			"\"image-scaled\"", "\"image-scaled-ratio-max\"",
			"\"image-scaled-ratio-min\"", "\"none\"", "\"normal\"",
			"\"truncated\"", "\"zoom-range\"", "\"at-zoom\"", "\"under-zoom\"",
			"\"over-zoom\"", "\"zooms\"", "\"fit\"", "\"bold\"",
			"\"bold-italic\"", "\"italic\"", "\"along\"", "\"at-left\"",
			"\"at-right\"", "\"center\"", "\"left\"", "\"right\"", "\"under\"",
			"\"above\"", "\"justify\"", "\"circle\"", "\"triangle\"",
			"\"freeplane\"", "\"text-box\"", "\"text-rounded-box\"",
			"\"text-circle\"", "\"text-diamond\"", "\"text-paragraph\"",
			"\"box\"", "\"rounded-box\"", "\"cross\"", "\"diamond\"",
			"\"polygon\"", "\"button\"", "\"text-field\"", "\"panel\"",
			"\"line\"", "\"polyline\"", "\"angle\"", "\"cubic-curve\"",
			"\"blob\"", "\"arrow\"", "\"flow\"", "\"pie-chart\"", "\"image\"",
			"\"images\"", "\"from\"", "\"node0\"", "\"to\"", "\"node1\"",
			"\"projection\"", "\"clicked\"", "\"selected\"", "<IDENTIFIER>",
			"<COMMENT>", };

}
