/* Generated By:JavaCC: Do not edit this line. StyleSheetParserConstants.java */
package org.graphstream.ui.old.graphicGraph.stylesheet.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StyleSheetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int HEXDIGIT = 7;
  /** RegularExpression Id. */
  int UNITS = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int SHARP = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int COMA = 17;
  /** RegularExpression Id. */
  int RGBA = 18;
  /** RegularExpression Id. */
  int RGB = 19;
  /** RegularExpression Id. */
  int HTMLCOLOR = 20;
  /** RegularExpression Id. */
  int REAL = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int URL = 23;
  /** RegularExpression Id. */
  int GRAPH = 24;
  /** RegularExpression Id. */
  int EDGE = 25;
  /** RegularExpression Id. */
  int NODE = 26;
  /** RegularExpression Id. */
  int SPRITE = 27;
  /** RegularExpression Id. */
  int ARROWIMGURL = 28;
  /** RegularExpression Id. */
  int ARROWLENGTH = 29;
  /** RegularExpression Id. */
  int ARROWSHAPE = 30;
  /** RegularExpression Id. */
  int ARROWWIDTH = 31;
  /** RegularExpression Id. */
  int BGCOLOR = 32;
  /** RegularExpression Id. */
  int BORDERCOLOR = 33;
  /** RegularExpression Id. */
  int BORDERSTYLE = 34;
  /** RegularExpression Id. */
  int BORDERWIDTH = 35;
  /** RegularExpression Id. */
  int COLOR = 36;
  /** RegularExpression Id. */
  int NODESHAPE = 37;
  /** RegularExpression Id. */
  int EDGESHAPE = 38;
  /** RegularExpression Id. */
  int EDGESTYLE = 39;
  /** RegularExpression Id. */
  int HEIGHT = 40;
  /** RegularExpression Id. */
  int IMAGEMODE = 41;
  /** RegularExpression Id. */
  int IMAGEOFFSET = 42;
  /** RegularExpression Id. */
  int PADDING = 43;
  /** RegularExpression Id. */
  int SHADOWSTYLE = 44;
  /** RegularExpression Id. */
  int SHADOWWIDTH = 45;
  /** RegularExpression Id. */
  int SHADOWOFFSET = 46;
  /** RegularExpression Id. */
  int SHADOWCOLOR = 47;
  /** RegularExpression Id. */
  int SPRITESHAPE = 48;
  /** RegularExpression Id. */
  int SPRITEORIENT = 49;
  /** RegularExpression Id. */
  int TEXTALIGN = 50;
  /** RegularExpression Id. */
  int TEXTCOLOR = 51;
  /** RegularExpression Id. */
  int TEXTMODE = 52;
  /** RegularExpression Id. */
  int TEXTSTYLE = 53;
  /** RegularExpression Id. */
  int TEXTFONT = 54;
  /** RegularExpression Id. */
  int TEXTSIZE = 55;
  /** RegularExpression Id. */
  int TEXTOFFSET = 56;
  /** RegularExpression Id. */
  int WIDTH = 57;
  /** RegularExpression Id. */
  int ZINDEX = 58;
  /** RegularExpression Id. */
  int ALONG = 59;
  /** RegularExpression Id. */
  int ANGLE = 60;
  /** RegularExpression Id. */
  int ARROW = 61;
  /** RegularExpression Id. */
  int ASIDE = 62;
  /** RegularExpression Id. */
  int BOLD = 63;
  /** RegularExpression Id. */
  int BOLD_ITALIC = 64;
  /** RegularExpression Id. */
  int CENTER = 65;
  /** RegularExpression Id. */
  int CIRCLE = 66;
  /** RegularExpression Id. */
  int CLICKED = 67;
  /** RegularExpression Id. */
  int CROSS = 68;
  /** RegularExpression Id. */
  int CUBICCURVE = 69;
  /** RegularExpression Id. */
  int DASHES = 70;
  /** RegularExpression Id. */
  int DIAMANT = 71;
  /** RegularExpression Id. */
  int DOTS = 72;
  /** RegularExpression Id. */
  int FLOW = 73;
  /** RegularExpression Id. */
  int FROM = 74;
  /** RegularExpression Id. */
  int HIDDEN = 75;
  /** RegularExpression Id. */
  int TRUNCATED = 76;
  /** RegularExpression Id. */
  int IMAGE = 77;
  /** RegularExpression Id. */
  int IMAGES = 78;
  /** RegularExpression Id. */
  int ITALIC = 79;
  /** RegularExpression Id. */
  int LEFT = 80;
  /** RegularExpression Id. */
  int LINE = 81;
  /** RegularExpression Id. */
  int NONE = 82;
  /** RegularExpression Id. */
  int NORMAL = 83;
  /** RegularExpression Id. */
  int ORIGIN = 84;
  /** RegularExpression Id. */
  int PLAIN = 85;
  /** RegularExpression Id. */
  int RIGHT = 86;
  /** RegularExpression Id. */
  int SELECTED = 87;
  /** RegularExpression Id. */
  int SIMPLE = 88;
  /** RegularExpression Id. */
  int SQUARE = 89;
  /** RegularExpression Id. */
  int TEXTBOX = 90;
  /** RegularExpression Id. */
  int TEXTELLIPSE = 91;
  /** RegularExpression Id. */
  int TRIANGLE = 92;
  /** RegularExpression Id. */
  int TILED = 93;
  /** RegularExpression Id. */
  int PIE_CHART = 94;
  /** RegularExpression Id. */
  int TO = 95;
  /** RegularExpression Id. */
  int IDENTIFIER = 96;
  /** RegularExpression Id. */
  int COMMENT = 97;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<EOL>",
    "<DIGIT>",
    "<HEXDIGIT>",
    "<UNITS>",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"#\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "<RGBA>",
    "<RGB>",
    "<HTMLCOLOR>",
    "<REAL>",
    "<STRING>",
    "\"url\"",
    "\"graph\"",
    "\"edge\"",
    "\"node\"",
    "\"sprite\"",
    "\"arrow-image\"",
    "\"arrow-length\"",
    "\"arrow-shape\"",
    "\"arrow-width\"",
    "\"background-color\"",
    "\"border-color\"",
    "\"border-style\"",
    "\"border-width\"",
    "\"color\"",
    "\"node-shape\"",
    "\"edge-shape\"",
    "\"edge-style\"",
    "\"height\"",
    "\"image-mode\"",
    "\"image-offset\"",
    "\"padding\"",
    "\"shadow-style\"",
    "\"shadow-width\"",
    "\"shadow-offset\"",
    "\"shadow-color\"",
    "\"sprite-shape\"",
    "\"sprite-orientation\"",
    "\"text-align\"",
    "\"text-color\"",
    "\"text-mode\"",
    "\"text-style\"",
    "\"text-font\"",
    "\"text-size\"",
    "\"text-offset\"",
    "\"width\"",
    "\"z-index\"",
    "\"along\"",
    "\"angle\"",
    "\"arrow\"",
    "\"aside\"",
    "\"bold\"",
    "\"bold-italic\"",
    "\"center\"",
    "\"circle\"",
    "\"clicked\"",
    "\"cross\"",
    "\"cubic-curve\"",
    "\"dashes\"",
    "\"diamant\"",
    "\"dots\"",
    "\"flow\"",
    "\"from\"",
    "\"hidden\"",
    "\"truncated\"",
    "\"image\"",
    "\"images\"",
    "\"italic\"",
    "\"left\"",
    "\"line\"",
    "\"none\"",
    "\"normal\"",
    "\"origin\"",
    "\"plain\"",
    "\"right\"",
    "\"selected\"",
    "\"simple\"",
    "\"square\"",
    "\"text-box\"",
    "\"text-ellipse\"",
    "\"triangle\"",
    "\"tiled\"",
    "\"pie-chart\"",
    "\"to\"",
    "<IDENTIFIER>",
    "<COMMENT>",
  };

}
